name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
  
    - name: Build distribution packages
      run: |
        # mkdir -p ~/.ssh
        # echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        # chmod 600 ~/.ssh/id_rsa
        # ssh ubuntu@52.208.43.242
        # mkdir all_work
        mkdir -p ~/.ssh
        echo ${ secrets.PRIVATE_KEY } | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 52.208.43.242 >> ~/.ssh/known_hosts
        ssh ubuntu@52.208.43.242 "mkdir all_work; exit"
