stages:
  - test
  - push

test:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  artifacts:
    paths:
      - test-reports/
    reports:
      junit:
        - test-reports/*.xml

push:
  stage: push
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" != "main" ]; then
        echo "Changes are not on main branch, skipping push"
        exit 0
      fi
    - git push